accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/',views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('forgot-password/', views.ForgotPassword.as_view(), name='forgot-password'),
    path('forgot-password/<email>/', views.ForgotPasswordReset.as_view(), name='forgot-password-reset'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/edit/', views.EditProfile.as_view(), name='edit-profile'),
    path('profile/update-picture/', views.UpdateProfilePicture.as_view(), name='update-picture'),
    path('become-seller/',views.BecomeSeller.as_view(), name='become-seller'),
    path('become-reseller/',views.BecomeReseller.as_view(), name='become-reseller'),
    
    path('profile/verify-user-email/',views.VerifyUserEmail.as_view(),name='verify-user-email'),
]

farozamart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views
from store.api.routes import router as storeRouter
from accounts.api.routes import router as accountsRouter

router = DefaultRouter()
router.registry.extend(storeRouter.registry)
router.registry.extend(accountsRouter.registry)

urlpatterns = [
    path('favicon.ico',RedirectView.as_view(url=staticfiles_storage.url('favicon.png'))),
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('store/', include('store.urls')),
    path('dropshipping/',include('dropshipping.urls')),
    path('paymentgateway/',include('paymentgateway.urls')),
    path('api/v1/',include(router.urls)),
    path('api/auth/login/',views.obtain_auth_token)
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views as homeViews

app_name="home"
urlpatterns = [
    path('', homeViews.Home.as_view(), name='home'),
]

store/urls.py
from django.urls import path
from store import views

app_name='store'
urlpatterns = [
  # customer
  path('shop/',views.Shop.as_view(),name='shop'),
  path('shop/listing/<id>/',views.Listing.as_view(),name='listing'),
  path('shop/cart/',views.Cart.as_view(),name='cart'),
  path('shop/checkout/payment/',views.CheckoutPayment.as_view(),name='checkout-payment'),
  path('shop/cart/<id>/edit/',views.EditCartItem.as_view(),name='edit-cart-item'),
  path('shop/cart/<id>/delete/',views.DeleteCartItem.as_view(),name='delete-cart-item'),
  path('shop/cart/checkout/<order>/',views.Checkout.as_view(),name='checkout'),
  path('shop/cart/checkout-cod/<order>/',views.CheckoutCOD.as_view(),name='checkout-cod'),
  
  path('profile/orders/',views.CustomerOrders.as_view(),name='customer-orders'),
  path('profile/orders/<id>/',views.SingleCustomerOrder.as_view(),name='customer-order'),

  path('become-seller/',views.BecomeSeller.as_view(),name='become-seller'),
  path('become-reseller/',views.BecomeReseller.as_view(),name='become-reseller'),
  path('become-reseller-success/',views.BecomeResellerSuccess.as_view(),name='become-reseller-success'),
  
  # staff
  path('dashboard/orders/',views.StaffOrders.as_view(),name='staff-orders'),
  path('dashboard/orders/<id>/',views.StaffOrder.as_view(),name='staff-order'),
  path('dashboard/orders/<id>/comfirm/',views.StaffComfirmOrder.as_view(),name='staff-comfirm-order'),
  path('dashboard/orders/<id>/decline/',views.StaffDeclineOrder.as_view(),name='staff-decline-order'),
  path('dashboard/orders/<id>/approve/',views.StaffApproveOrder.as_view(),name='staff-approve-order'),
  path('dashboard/orders/<id>/cancel/',views.StaffCancelOrder.as_view(),name='staff-cancel-order'),
  path('dashboard/orders/<id>/deliver/',views.StaffDeliverOrder.as_view(),name='staff-deliver-order'),
  path('dashboard/orders/<id>/delivery-failed/',views.StaffDeliveryFailed.as_view(),name='staff-delivery-failed'),
  
  path('dashboard/withdraws/',views.StaffWithdraws.as_view(),name='staff-withdraws'),
  path('dashboard/withdraws/<pk>/approve/',views.StaffApproveWithdraw.as_view(),name='staff-approve-withdraws'),
  
  path('dashboard/sellers/',views.StaffSellers.as_view(),name='staff-sellers'),
  path('dashboard/sellers/requests/<pk>/',views.StaffSellerRequest.as_view(),name='staff-seller-request'),
  path('dashboard/sellers/<pk>/approve/',views.StaffApproveSeller.as_view(),name='staff-approve-seller'),
  path('dashboard/sellers/<pk>/decline/',views.StaffDeclineSellerRequest.as_view(),name='staff-decline-seller'),
  
  path('dashboard/resellers/',views.StaffResellers.as_view(),name='staff-resellers'),
  path('dashboard/resellers/<pk>/approve/',views.StaffApproveReseller.as_view(),name='staff-approve-reseller'),
  path('dashboard/resellers/<pk>/decline/',views.StaffDeclineResellerRequest.as_view(),name='staff-decline-reseller'),
  
  path('dashboard/currencies/',views.Currencies.as_view(),name='currencies'),
  path('dashboard/currencies/new/',views.NewCurrency.as_view(),name='new-currency'),
  path('dashboard/currencies/<id>/edit/',views.EditCurrency.as_view(),name='edit-currency'),
  path('dashboard/currencies/<id>/delete/',views.DeleteCurrency.as_view(),name='delete-currency'),
  
  path('dashboard/users/',views.StaffUsers.as_view(),name='staff-users'),
  path('dashboard/users/id/<user_id>/',views.StaffGeneralProfile.as_view(),name='staff-user'),
  path('dashboard/users/id/<user_id>/block-unblock/',views.StaffBlocOrUnblockUser.as_view(),name='staff-block-unblock-user'),
  
  path('dashboard/receiving-accounts/',views.StaffRecevingAccounts.as_view(),name='staff-receiving-accounts'),
  
  # seller
  path('dashboard/inventory/',views.Inventory.as_view(),name='inventory'),
  path('dashboard/new-inventory/',views.NewInventory.as_view(),name='new-inventory'),
  path('dashboard/inventory/<id>/images/',views.InventoryImages.as_view(),name='inventory-images'),
  path('dashboard/inventory/<id>/edit/',views.EditInventory.as_view(),name='edit-inventory'),
  path('dashboard/inventory/<id>/delete/',views.DeleteInventory.as_view(),name='delete-inventory'),
  
  path('dashboard/categories/',views.Categories.as_view(),name='categories'),
  path('dashboard/categories/new/',views.NewCategory.as_view(),name='new-category'),
  path('dashboard/categories/<id>/edit/',views.EditCategory.as_view(),name='edit-category'),
  path('dashboard/categories/<id>/delete/',views.DeleteCategory.as_view(),name='delete-category'),
  
  path('dashboard/purchases/',views.Purchases.as_view(),name='purchases'),
  path('dashboard/purchases/new/',views.NewPurchase.as_view(),name='new-purchase'),
  path('dashboard/purchases/<id>/edit/',views.EditPurchase.as_view(),name='edit-purchase'),
  path('dashboard/purchases/<id>/delete/',views.DeletePurchase.as_view(),name='delete-purchase'),
  
  path('dashboard/sales/',views.Sales.as_view(),name='sales'),
  path('dashboard/sales/wallet/<currency_code>/',views.StoreWallet.as_view(),name='store-wallet'),
  path('dashboard/sales/new/',views.NewSale.as_view(),name='new-sale'),
  path('dashboard/sales/<id>/',views.SalesItem.as_view(),name='sales-item'),
  path('dashboard/sales/<id>/edit/',views.EditSale.as_view(),name='edit-sale'),
  path('dashboard/sales/<id>/delete/',views.DeleteSale.as_view(),name='delete-sale'),
  path('dashboard/sales/order/<id>/',views.SalesOrder.as_view(),name='sales-order'),
  path('dashboard/sales/withdraw/<currency_id>/',views.StoreWithdraw.as_view(),name='sales-withdraw-request'),
  path('dashboard/sales/withdraw/cancel/<id>/',views.CancelWithdraw.as_view(),name='sales-cancel-withdraw-request'),
  
  path('dashboard/store-accounts/',views.StoreAccounts.as_view(),name='store-accounts'),
  path('dashboard/store-accounts/create/',views.CreateStoreAccount.as_view(),name='create-store-account'),
  
  # reseller
  path('dashboard/resale/',views.Resales.as_view(),name='resales'),
  path('dashboard/resale/wallet/<currency_code>/',views.UserWallet.as_view(),name='user-wallet'),
  path('dashboard/resale/<id>/delete',views.DeleteResale.as_view(),name='delete-resale'),
  path('dahsboard/resale/purchases/',views.ResalePurchases.as_view(),name='resale-purchases'),
  path('dahsboard/resale/purchases/<id>/',views.ResalePurchase.as_view(),name='resale-purchase'),
  path('dahsboard/resale/purchases/<id>/resale/',views.NewResale.as_view(),name='new-resale'),
  
  path('dashboard/reseller/cart/',views.ResellerCart.as_view(),name='reseller-cart'),
  path('dashboard/reseller/cart/clear/',views.ClearResellerCart.as_view(),name='clear-reseller-cart'),
  path('dashboard/reseller/cart/cod-checkout/',views.ResellerCODCheckout.as_view(),name='reseller-cod-checkout'),
  
  path('dashboard/user-accounts/',views.UserAccounts.as_view(),name='user-accounts'),
  path('dashboard/user-accounts/create/',views.CreateUserAccount.as_view(),name='create-user-account'),
]

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from store.models import Store
from rest_framework.authtoken.models import Token

# Create your models here.
gender_options = (
  ('Male','Male'),
  ('Female','Female')
)
class Profile(models.Model):
  user=models.OneToOneField(to=User,on_delete=models.CASCADE,related_name='profile')
  gender=models.CharField(max_length=200,choices=gender_options,default='Male')
  address=models.CharField(max_length=200,null=True)
  email=models.EmailField()
  user_email_verified=models.BooleanField(default=False)
  profile_email_verified=models.BooleanField(default=False)
  phone=models.CharField(max_length=200,null=True)
  whatsapp=models.CharField(max_length=200,null=True)
  facebook_url=models.URLField(null=True)
  is_seller=models.BooleanField(default=False)
  is_reseller=models.BooleanField(default=False)
  picture=models.ImageField(upload_to='profile/pictures',default='profile/default.png')
  
  def full_name(self):
    return f"{self.user.first_name} {self.user.last_name}"
  
  @receiver(post_save, sender=User)
  def _post_save_receiver(sender, instance, created, **kwargs):
    if(created):
      Profile.objects.create(user=instance,email=instance.email)
      Token.objects.create(user=instance)
    else:
      instance.profile.save()

accounts/api/routes.py
from rest_framework.routers import DefaultRouter
from accounts.api import views

router = DefaultRouter()
router.register(r'accounts/token-user',views.TokenUser,basename='token-user')
router.register(r'accounts/registration',views.RegisterUser,basename='registration')

accounts/api/views.py
from rest_framework.viewsets import ViewSet
from rest_framework.response import Response
from accounts.api import serializers
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
from rest_framework.decorators import action
from accounts.forms import RegistrationForm

class TokenUser(ViewSet):
  def list(self,request,*args,**kwargs):
    userSerializer = serializers.UserSerializer(instance=request.user)
    return Response(userSerializer.data)

class RegisterUser(ViewSet):
  authentication_classes=[]
  permission_classes=[]
  @action(detail=False,methods=['post'])
  def register(self,request):
    form = RegistrationForm(data=request.POST)
    if form.is_valid():
      form.save()
      return Response(data={'registered':True})
    
    return Response(data=form.errors)

store/api/routes.py
from rest_framework.routers import DefaultRouter
from store.api import views as apiviews

router = DefaultRouter()
router.register(r'store/listing',apiviews.ListingViewSet,basename='store')
router.register(r'store/cart',viewset=apiviews.CartViewSet,basename='cart')

store/api/views.py
from rest_framework.viewsets import ViewSet
from rest_framework.response import Response
from rest_framework.decorators import action
from store import models, functions
from store.api import serializers
from django.shortcuts import get_object_or_404

class ListingViewSet(ViewSet):
  def list(self,request,*args,**kwargs):
    listing = models.Purchase.objects.all()
    listingSerializer = serializers.PurchaseSerializer(listing, many=True)
    return Response(listingSerializer.data)
  
  def retrieve(self,request,pk,*args,**kwargs):
    listing = models.Purchase.objects.get(pk=pk)
    listingSerializer = serializers.PurchaseSerializer(listing)
    return Response(listingSerializer.data)
  
  @action(detail=True,methods=['post'])
  def add_to_cart(self,request,pk):
    listing = models.Purchase.objects.get(pk=pk)
    serializer = serializers.AddToCartSerializer(user=request.user,listing=listing,data=request.POST)
    if serializer.is_valid():
      serializer.save()
      sales = models.Sale.objects.filter(user=request.user,cart=True,approved=False)
      saleSerializer = serializers.SalesSerializer(sales,many=True)
      return Response(saleSerializer.data)
    return Response(serializer.error_messages,status=500)

class CartViewSet(ViewSet):
  @action(detail=False,methods=['get'])
  def get_cart(self,request,*args,**kwargs):
    order = request.user.orders.get(draft=True)
    orderSerializer = serializers.OrderSerializer(order)
    return Response(orderSerializer.data)
  
  @action(detail=True,methods=['get'])
  def cod_checkout(self,request,pk,*args,**kwargs):
    order = functions.CODPayment(pk=pk)
    orderSerializer = serializers.OrderSerializer(order)
    return Response(orderSerializer.data)
    

store/templates/store/tables/accounts.html
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Accounts</h3>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th>Bank Name</th>
        <th>Bank Address</th>
        <th>Routing</th>
        <th>Account Number</th>
        <th>Account Type</th>
        <th>Account Name</th>
        <th></th>
      </tr>
      {% for account in accounts %}
      <tr>
        <td>{{account.bank_name}}</td>
        <td>{{account.bank_address}}</td>
        <td>{{account.routing}}</td>
        <td>{{account.account_number}}</td>
        <td>{{account.account_type}}</td>
        <td>{{account.account_name}}</td>
        <td>
          <a href="" class="btn btn-primary">Edit</a>
          <a href="" class="btn btn-danger">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/categories.html

<div class="box">
  <div class="box-header">
    <h3 class="box-title">Categories</h3>
    <div class="box-tools">
      <div class="input-group">
        <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <a href="{% url "store:new-category" %}" class="btn btn-primary mx-2">New Category</a>
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Inventory</th>
        <th></th>
      </tr>
      {% for category in categories %}
      <tr>
        <td>{{category.id}}</td>
        <td>{{category.name}}</td>
        <td>{{category.inventory.all.count}}</td>
        <td>
          {% if user.id == category.user.id %}
          <a href="{% url "store:edit-category" id=category.id %}" class="btn btn-primary">Edit</a>
          <a href="{% url "store:delete-category" id=category.id %}" class="btn btn-danger">Delete</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/currencies.html

<div class="box">
  <div class="box-header">
    <h3 class="box-title">Currencies</h3>
    <div class="box-tools">
      <div class="input-group">
        <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <a href="{% url "store:new-currency" %}" class="btn btn-primary mx-2">New Currency</a>
    <table class="table table-hover">
      <tr>
        <th>Symbol</th>
        <th>Name</th>
        <th>code</th>
        <th></th>
      </tr>
      {% for currency in currencies %}
      <tr>
        <td>{{currency.symbol}}</td>
        <td>{{currency.name_singular}}</td>
        <td>{{currency.code}}</td>
        <td>
          <a href="{% url "store:edit-currency" id=currency.id %}" class="btn btn-primary">Edit</a>
          <a href="{% url "store:delete-currency" id=currency.id %}" class="btn btn-danger">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/inventory_items.html
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Inventory Items</h3>
    <div class="box-tools">
      <div class="input-group">
        <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <a href="{% url "store:new-inventory" %}" class="btn btn-primary mx-2">New Item</a>
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Store</th>
        <th>Name</th>
        <th>Category</th>
        <th></th>
        <th></th>
      </tr>
      {% for inventory_item in inventory_items %}
      <tr>
        <td>{{inventory_item.id}}</td>
        <td>{{inventory_item.store.name}}</td>
        <td>{{inventory_item.name}}</td>
        <td>{{inventory_item.category.name}}</td>
        <td><img src="{{inventory_item.picture.url}}" witdth=50 height=50 alt="{{inventory_item.name}}" /></td>
        <td>
          <a href="{% url "store:new-purchase" %}?inventory_id={{inventory_item.id}}" class="btn btn-primary">Add stock</a>
          <a href="{% url "store:inventory-images" id=inventory_item.id %}" class="btn btn-primary">Images</a>
          <a href="{% url "store:edit-inventory" id=inventory_item.id %}" class="btn btn-primary">Edit</a>
          <a href="{% url "store:delete-inventory" id=inventory_item.id %}" class="btn btn-danger">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/orders.html
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Orders</h3>
    <div class="box-tools">
      <div class="input-group">
        <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body">
    <div class="table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>ID</th>
          <th>Customer</th>
          <th>Cost</th>
          <th>Status</th>
          <th></th>
        </tr>
        {% for order in orders %}
        <tr>
          <td>{{order.id}}</td>
          <td>{{order.user.profile.full_name}}</td>
          <td>{{order.total_cost_number}}</td>
          <td>{{order.status}}</td>
          <td>
            {% if user.is_staff %}
              {% if order.status == 'PENDING' %}
              <a href="{% url "store:staff-comfirm-order" id=order.id %}" class="btn btn-success">Comfirm</a>
              <a href="{% url "store:staff-decline-order" id=order.id %}" class="btn btn-danger">Decline</a>
              {% elif order.status == 'COMFIRMED' %}
              <a href="{% url "store:staff-approve-order" id=order.id %}" class="btn btn-success">Complete</a>
              <a href="{% url "store:staff-delivery-failed" id=order.id %}" class="btn btn-warning">Delivery failed</a>
              {% endif %}
            {% endif %}
            <a href="{% url "store:staff-order" id=order.id %}" class="btn btn-primary">View Order</a>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div><!-- /.box-body -->
  </div>
</div><!-- /.box -->

store/templates/store/tables/resale-purchases.html

<div class="box">
  <div class="box-header">
    <h3 class="box-title">Resale Purchases</h3>
    <div class="box-tools">
      <div class="input-group">
        <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Inventory</th>
        <th></th>
        <th>Quantity</th>
        <th>Resale Price</th>
        <th></th>
      </tr>
      {% for purchase in purchases %}
      <tr>
        <td>{{purchase.id}}</td>
        <td>{{purchase.inventory.name}}</td>
        <td><img src="{{purchase.inventory.picture.url}}" alt="{{purchase.inventory.name}}" height=50 /></td>
        <td>{{purchase.quantity}}</td>
        <td>{{purchase.get_resale_price}}</td>
        <td>
          <a href="{% url "store:resale-purchase" id=purchase.id %}" class="btn btn-primary">View</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/resales.html

<div class="box">
  <div class="box-header">
    <h3 class="box-title">Resales</h3>
    <div class="box-tools">
      <div class="input-group">
        <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Product</th>
        <th></th>
        <th>Resale Price</th>
        <th>Sale Price</th>
        <th></th>
      </tr>
      {% for resale in resales %}
      <tr>
        <td>{{resale.id}}</td>
        <td>{{resale.purchase.inventory.name}}</td>
        <td><img src="{{resale.purchase.inventory.picture.url}}" alt="{{resale.purchase.inventory.name}}" height=50/></td>
        <td>{{resale.purchase.get_resale_price}}</td>
        <td>{{resale.get_sale_price}}</td>
        <td>
          <a href="{% url "store:delete-resale" id=resale.id %}" class="btn btn-danger">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/store-wallets.html
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Store Wallets</h3>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th>Balance</th>
        <th>Currency</th>
        <th></th>
      </tr>
      {% for wallet in store_wallets %}
      <tr>
        <td>{{wallet.balance_after}}</td>
        <td>{{wallet.currency.code}}</td>
        <td>
          <a href="{% url "store:sales-withdraw-request" currency_id=wallet.currency.id %}" class="btn btn-primary">Withdraw</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/user-orders.html

<table class="table">
  <thead>
    <th>ID</th>
    <th>Items Count</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Status</th>
  </thead>
  <tbody>
    {% for order in user.orders.all %}
    <tr>
      <td><a href="{% url "store:customer-order" id=order.id %}">{{order.id}}</a></td>
      <td>{{order.sales.all.count}}</td>
      <td>{{order.created_at}}</td>
      <td>{{order.updated_at}}</td>
      <td>{{order.status}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

store/templates/store/tables/wallets.html

<div class="box">
  <div class="box-header">
    <h3 class="box-title">Wallets</h3>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Balance</th>
        <th>Currency</th>
        <th></th>
      </tr>
      {% for wallet in store_wallets %}
      <tr>
        <td>{{wallet.id}}</td>
        <td>{{wallet.balance_after}}</td>
        <td>{{wallet.currency.code}}</td>
        <td>
          <a href="{% url "store:sales-withdraw-request" currency_id=wallet.currency.id %}" class="btn btn-primary">Withdraw</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->

store/templates/store/tables/withdraws.html
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Withdraw</h3>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Amount</th>
        <th>BKASH</th>
        <th>NID Card</th>
        <th>Status</th>
        <th></th>
      </tr>
      {% for withdraw in withdraws %}
      {% if not withdraw.approved %}
      <tr>
        <td>{{withdraw.id}}</td>
        <td>{{withdraw.amount}}</td>
        <td>{{withdraw.bkash_number}}</td>
        <td><a href="{{withdraw.nid_card.url}}"><img src="{{withdraw.nid_card.url}}" height=50 /></a></td>
        <td>{{withdraw.status}}</td>
        <td>
          {% if withdraw.status == 'PENDING' %}
          <a href="{% url "store:sales-cancel-withdraw-request" id=withdraw.id %}" class="btn btn-danger">Cancel</a>
          {% endif %}
        </td>
      </tr>
      {% endif %}
      {% endfor %}
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->