accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/',views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('forgot-password/', views.ForgotPassword.as_view(), name='forgot-password'),
    path('forgot-password/<email>/', views.ForgotPasswordReset.as_view(), name='forgot-password-reset'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/edit/', views.EditProfile.as_view(), name='edit-profile'),
    path('profile/update-picture/', views.UpdateProfilePicture.as_view(), name='update-picture'),
    path('become-seller/',views.BecomeSeller.as_view(), name='become-seller'),
    path('become-reseller/',views.BecomeReseller.as_view(), name='become-reseller'),
    
    path('profile/verify-user-email/',views.VerifyUserEmail.as_view(),name='verify-user-email'),
]

dashboard/urls.py
from django.urls import path, include
from dashboard import views

app_name="dashboard"
urlpatterns = [
  path('',views.Dashboard.as_view(),name="dashboard"),
  path('settings/',views.GeneralSettings.as_view(),name='general-settings'),
  path('mailing-settings/',views.Mailing.as_view(),name='mailing-settings'),
]

farozamart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views
from store.api.routes import router as storeRouter
from accounts.api.routes import router as accountsRouter

router = DefaultRouter()
router.registry.extend(storeRouter.registry)
router.registry.extend(accountsRouter.registry)

urlpatterns = [
    path('favicon.ico',RedirectView.as_view(url=staticfiles_storage.url('favicon.png'))),
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('store/', include('store.urls')),
    path('dropshipping/',include('dropshipping.urls')),
    path('paymentgateway/',include('paymentgateway.urls')),
    path('api/v1/',include(router.urls)),
    path('api/auth/login/',views.obtain_auth_token)
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views as homeViews

app_name="home"
urlpatterns = [
    path('', homeViews.Home.as_view(), name='home'),
]

store/urls.py
from django.urls import path
from store import views

app_name='store'
urlpatterns = [
  # customer
  path('shop/',views.Shop.as_view(),name='shop'),
  path('shop/listing/<id>/',views.Listing.as_view(),name='listing'),
  path('shop/cart/',views.Cart.as_view(),name='cart'),
  path('shop/checkout/payment/',views.CheckoutPayment.as_view(),name='checkout-payment'),
  path('shop/cart/<id>/edit/',views.EditCartItem.as_view(),name='edit-cart-item'),
  path('shop/cart/<id>/delete/',views.DeleteCartItem.as_view(),name='delete-cart-item'),
  path('shop/cart/checkout/<order>/',views.Checkout.as_view(),name='checkout'),
  path('shop/cart/checkout-cod/<order>/',views.CheckoutCOD.as_view(),name='checkout-cod'),
  
  path('profile/orders/',views.CustomerOrders.as_view(),name='customer-orders'),
  path('profile/orders/<id>/',views.SingleCustomerOrder.as_view(),name='customer-order'),

  path('become-seller/',views.BecomeSeller.as_view(),name='become-seller'),
  path('become-reseller/',views.BecomeReseller.as_view(),name='become-reseller'),
  path('become-reseller-success/',views.BecomeResellerSuccess.as_view(),name='become-reseller-success'),
  
  # staff
  path('dashboard/orders/',views.StaffOrders.as_view(),name='staff-orders'),
  path('dashboard/orders/<id>/',views.StaffOrder.as_view(),name='staff-order'),
  path('dashboard/orders/<id>/comfirm/',views.StaffComfirmOrder.as_view(),name='staff-comfirm-order'),
  path('dashboard/orders/<id>/decline/',views.StaffDeclineOrder.as_view(),name='staff-decline-order'),
  path('dashboard/orders/<id>/approve/',views.StaffApproveOrder.as_view(),name='staff-approve-order'),
  path('dashboard/orders/<id>/cancel/',views.StaffCancelOrder.as_view(),name='staff-cancel-order'),
  path('dashboard/orders/<id>/deliver/',views.StaffDeliverOrder.as_view(),name='staff-deliver-order'),
  path('dashboard/orders/<id>/delivery-failed/',views.StaffDeliveryFailed.as_view(),name='staff-delivery-failed'),
  
  path('dashboard/withdraws/',views.StaffWithdraws.as_view(),name='staff-withdraws'),
  path('dashboard/withdraws/<pk>/approve/',views.StaffApproveWithdraw.as_view(),name='staff-approve-withdraws'),
  
  path('dashboard/sellers/',views.StaffSellers.as_view(),name='staff-sellers'),
  path('dashboard/sellers/requests/<pk>/',views.StaffSellerRequest.as_view(),name='staff-seller-request'),
  path('dashboard/sellers/<pk>/approve/',views.StaffApproveSeller.as_view(),name='staff-approve-seller'),
  path('dashboard/sellers/<pk>/decline/',views.StaffDeclineSellerRequest.as_view(),name='staff-decline-seller'),
  
  path('dashboard/resellers/',views.StaffResellers.as_view(),name='staff-resellers'),
  path('dashboard/resellers/<pk>/approve/',views.StaffApproveReseller.as_view(),name='staff-approve-reseller'),
  path('dashboard/resellers/<pk>/decline/',views.StaffDeclineResellerRequest.as_view(),name='staff-decline-reseller'),
  
  path('dashboard/currencies/',views.Currencies.as_view(),name='currencies'),
  path('dashboard/currencies/new/',views.NewCurrency.as_view(),name='new-currency'),
  path('dashboard/currencies/<id>/edit/',views.EditCurrency.as_view(),name='edit-currency'),
  path('dashboard/currencies/<id>/delete/',views.DeleteCurrency.as_view(),name='delete-currency'),
  
  path('dashboard/users/',views.StaffUsers.as_view(),name='staff-users'),
  path('dashboard/users/id/<user_id>/',views.StaffGeneralProfile.as_view(),name='staff-user'),
  path('dashboard/users/id/<user_id>/block-unblock/',views.StaffBlocOrUnblockUser.as_view(),name='staff-block-unblock-user'),
  
  path('dashboard/receiving-accounts/',views.StaffRecevingAccounts.as_view(),name='staff-receiving-accounts'),
  
  # seller
  path('dashboard/inventory/',views.Inventory.as_view(),name='inventory'),
  path('dashboard/new-inventory/',views.NewInventory.as_view(),name='new-inventory'),
  path('dashboard/inventory/<id>/images/',views.InventoryImages.as_view(),name='inventory-images'),
  path('dashboard/inventory/<id>/edit/',views.EditInventory.as_view(),name='edit-inventory'),
  path('dashboard/inventory/<id>/delete/',views.DeleteInventory.as_view(),name='delete-inventory'),
  
  path('dashboard/categories/',views.Categories.as_view(),name='categories'),
  path('dashboard/categories/new/',views.NewCategory.as_view(),name='new-category'),
  path('dashboard/categories/<id>/edit/',views.EditCategory.as_view(),name='edit-category'),
  path('dashboard/categories/<id>/delete/',views.DeleteCategory.as_view(),name='delete-category'),
  
  path('dashboard/purchases/',views.Purchases.as_view(),name='purchases'),
  path('dashboard/purchases/new/',views.NewPurchase.as_view(),name='new-purchase'),
  path('dashboard/purchases/<id>/edit/',views.EditPurchase.as_view(),name='edit-purchase'),
  path('dashboard/purchases/<id>/delete/',views.DeletePurchase.as_view(),name='delete-purchase'),
  
  path('dashboard/sales/',views.Sales.as_view(),name='sales'),
  path('dashboard/sales/wallet/<currency_code>/',views.StoreWallet.as_view(),name='store-wallet'),
  path('dashboard/sales/new/',views.NewSale.as_view(),name='new-sale'),
  path('dashboard/sales/<id>/',views.SalesItem.as_view(),name='sales-item'),
  path('dashboard/sales/<id>/edit/',views.EditSale.as_view(),name='edit-sale'),
  path('dashboard/sales/<id>/delete/',views.DeleteSale.as_view(),name='delete-sale'),
  path('dashboard/sales/order/<id>/',views.SalesOrder.as_view(),name='sales-order'),
  path('dashboard/sales/withdraw/<currency_id>/',views.StoreWithdraw.as_view(),name='sales-withdraw-request'),
  path('dashboard/sales/withdraw/cancel/<id>/',views.CancelWithdraw.as_view(),name='sales-cancel-withdraw-request'),
  
  path('dashboard/store-accounts/',views.StoreAccounts.as_view(),name='store-accounts'),
  path('dashboard/store-accounts/create/',views.CreateStoreAccount.as_view(),name='create-store-account'),
  
  # reseller
  path('dashboard/resale/',views.Resales.as_view(),name='resales'),
  path('dashboard/resale/wallet/<currency_code>/',views.UserWallet.as_view(),name='user-wallet'),
  path('dashboard/resale/<id>/delete',views.DeleteResale.as_view(),name='delete-resale'),
  path('dahsboard/resale/purchases/',views.ResalePurchases.as_view(),name='resale-purchases'),
  path('dahsboard/resale/purchases/<id>/',views.ResalePurchase.as_view(),name='resale-purchase'),
  path('dahsboard/resale/purchases/<id>/resale/',views.NewResale.as_view(),name='new-resale'),
  
  path('dashboard/reseller/cart/',views.ResellerCart.as_view(),name='reseller-cart'),
  path('dashboard/reseller/cart/clear/',views.ClearResellerCart.as_view(),name='clear-reseller-cart'),
  path('dashboard/reseller/cart/cod-checkout/',views.ResellerCODCheckout.as_view(),name='reseller-cod-checkout'),
  
  path('dashboard/user-accounts/',views.UserAccounts.as_view(),name='user-accounts'),
  path('dashboard/user-accounts/create/',views.CreateUserAccount.as_view(),name='create-user-account'),
]

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from store.models import Store
from rest_framework.authtoken.models import Token

# Create your models here.
gender_options = (
  ('Male','Male'),
  ('Female','Female')
)
class Profile(models.Model):
  user=models.OneToOneField(to=User,on_delete=models.CASCADE,related_name='profile')
  gender=models.CharField(max_length=200,choices=gender_options,default='Male')
  address=models.CharField(max_length=200,null=True)
  email=models.EmailField()
  user_email_verified=models.BooleanField(default=False)
  profile_email_verified=models.BooleanField(default=False)
  phone=models.CharField(max_length=200,null=True)
  whatsapp=models.CharField(max_length=200,null=True)
  facebook_url=models.URLField(null=True)
  is_seller=models.BooleanField(default=False)
  is_reseller=models.BooleanField(default=False)
  picture=models.ImageField(upload_to='profile/pictures',default='profile/default.png')
  
  def full_name(self):
    return f"{self.user.first_name} {self.user.last_name}"
  
  @receiver(post_save, sender=User)
  def _post_save_receiver(sender, instance, created, **kwargs):
    if(created):
      Profile.objects.create(user=instance,email=instance.email)
      Token.objects.create(user=instance)
    else:
      instance.profile.save()

accounts/api/routes.py
from rest_framework.routers import DefaultRouter
from accounts.api import views

router = DefaultRouter()
router.register(r'accounts/token-user',views.TokenUser,basename='token-user')
router.register(r'accounts/registration',views.RegisterUser,basename='registration')

accounts/api/views.py
from rest_framework.viewsets import ViewSet
from rest_framework.response import Response
from accounts.api import serializers
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
from rest_framework.decorators import action
from accounts.forms import RegistrationForm

class TokenUser(ViewSet):
  def list(self,request,*args,**kwargs):
    userSerializer = serializers.UserSerializer(instance=request.user)
    return Response(userSerializer.data)

class RegisterUser(ViewSet):
  authentication_classes=[]
  permission_classes=[]
  @action(detail=False,methods=['post'])
  def register(self,request):
    form = RegistrationForm(data=request.POST)
    if form.is_valid():
      form.save()
      return Response(data={'registered':True})
    
    return Response(data=form.errors)

accounts/templates/accounts/edit-profile.html
{% extends "home/base.html" %}
{% block title %}Farozamart | Edit Profile{% endblock title %}

{% block content %}

<section class="layout_padding">
  <div class="container">
  {% include "home/includes/form.html" with method='POST' action='' submitText='Save' %}
  </div>
</section>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "home/base.html" %}

{% block title %}Farozamart | {{user.username}}{% endblock title %}

{% block styleSheets %}
{{block.super}}
<style>
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
</style>
{% endblock styleSheets %}

{% block content %}
<section class="">
  <div class="container emp-profile">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="{{user.profile.picture.url}}" alt="{{user.username}}"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                            <h5>
                                {{user.username}}
                            </h5>
                </div>
            </div>
            <div class="col-md-2">
                <a href='{% url "accounts:edit-profile" %}' class='btn btn-secondary m-2'>Edit Profile</a>
                {% if user.is_staff or user.profile.is_seller or user.profile.is_reseller %}
                <a href='{% url "dashboard:dashboard" %}' class="btn btn-primary my-2">Dashboard</a>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="">
                    <p>GENERAL</p>
                    <a href="{% url "accounts:profile" %}">Profile</a><br/>
                    <a href="{% url "accounts:update-picture" %}">Update Profile Picture</a>
                    <p>CUSTOMER</p>
                    <a href="{% url "store:customer-orders" %}">Orders</a><br/>
                </div>
            </div>
            <div class="col-md-8">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Orders</a>
                    </li>
                </ul>
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>User Id</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.id}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Name</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.first_name}} {{user.last_name}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Email</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.email}} {% if user.profile.user_email_verified %}<i class="fa fa-check" style="color:green;"></i> {% else %}<a class="btn btn-warning" href="{% url "accounts:verify-user-email" %}">Verify E-mail</a>{% endif %}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Phone</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.profile.phone}}</p>
                                    </div>
                                </div>
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        {% include "store/tables/user-orders.html" %}
                    </div>
                </div>
            </div>
        </div>         
    <center><a href="{% url "accounts:logout" %}" class="btn btn-danger">Logout</a></center>
</div>
</section>
{% endblock content %}

accounts/templates/accounts/update-picture.html
{% extends "home/base.html" %}
{% block title %}Farozamart | Update Picture{% endblock title %}

{% block content %}

<section class="layout_padding">
  <div class="container">
  {% include "includes/form.html" with method='POST' action='' submitText='Save' %}
  </div>
</section>

{% endblock content %}

accounts/templates/accounts/verify-user-email.html
{% extends "home/base.html" %}
{% block title %}Farozamart | Verify User Email{% endblock title %}

{% block content %}

<section class="layout_padding">
  <div class="container">
  {% include "home/includes/form.html" with method='POST' action='' submitText='Verify' %}
  <hr>
  <a href="" class="btn btn-primary">Resend Code</a>
  </div>
</section>

{% endblock content %}