accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/',views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('forgot-password/', views.ForgotPassword.as_view(), name='forgot-password'),
    path('forgot-password/<email>/', views.ForgotPasswordReset.as_view(), name='forgot-password-reset'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/edit/', views.EditProfile.as_view(), name='edit-profile'),
    path('profile/update-picture/', views.UpdateProfilePicture.as_view(), name='update-picture'),
    path('become-seller/',views.BecomeSeller.as_view(), name='become-seller'),
    path('become-reseller/',views.BecomeReseller.as_view(), name='become-reseller'),
    
    path('profile/verify-user-email/',views.VerifyUserEmail.as_view(),name='verify-user-email'),
]

dashboard/urls.py
from django.urls import path, include
from dashboard import views

app_name="dashboard"
urlpatterns = [
  path('',views.Dashboard.as_view(),name="dashboard"),
  path('settings/',views.GeneralSettings.as_view(),name='general-settings'),
  path('mailing-settings/',views.Mailing.as_view(),name='mailing-settings'),
]

dropshipping/urls.py
from django.urls import path
from dropshipping import views

app_name='dropshipping'
urlpatterns = [
    path('steadfast-configuration/',views.SteadfastConfiguration.as_view(),name="steadfast-configuration"),
    path('steadfast-delivery/',views.SteadfastDelivery.as_view(),name='steadfast-delivery'),
]

farozamart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views
from store.api.routes import router as storeRouter
from accounts.api.routes import router as accountsRouter

router = DefaultRouter()
router.registry.extend(storeRouter.registry)
router.registry.extend(accountsRouter.registry)

urlpatterns = [
    path('favicon.ico',RedirectView.as_view(url=staticfiles_storage.url('favicon.png'))),
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('store/', include('store.urls')),
    path('dropshipping/',include('dropshipping.urls')),
    path('paymentgateway/',include('paymentgateway.urls')),
    path('api/v1/',include(router.urls)),
    path('api/auth/login/',views.obtain_auth_token)
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views as homeViews

app_name="home"
urlpatterns = [
    path('', homeViews.Home.as_view(), name='home'),
]

paymentgateway/urls.py
from django.urls import path
from paymentgateway import views

app_name='paymentgateway'
urlpatterns = [
    path('payment-methods/',views.PaymentMethods.as_view(),name='payment-methods'),
    path('cod-pwyment/',views.CODPayment.as_view(),name='cod-payment'),
]

store/urls.py
from django.urls import path
from store import views

app_name='store'
urlpatterns = [
  # customer
  path('shop/',views.Shop.as_view(),name='shop'),
  path('shop/listing/<id>/',views.Listing.as_view(),name='listing'),
  path('shop/cart/',views.Cart.as_view(),name='cart'),
  path('shop/checkout/payment/',views.CheckoutPayment.as_view(),name='checkout-payment'),
  path('shop/cart/<id>/edit/',views.EditCartItem.as_view(),name='edit-cart-item'),
  path('shop/cart/<id>/delete/',views.DeleteCartItem.as_view(),name='delete-cart-item'),
  path('shop/cart/checkout/<order>/',views.Checkout.as_view(),name='checkout'),
  path('shop/cart/checkout-cod/<order>/',views.CheckoutCOD.as_view(),name='checkout-cod'),
  
  path('profile/orders/',views.CustomerOrders.as_view(),name='customer-orders'),
  path('profile/orders/<id>/',views.SingleCustomerOrder.as_view(),name='customer-order'),

  path('become-seller/',views.BecomeSeller.as_view(),name='become-seller'),
  path('become-reseller/',views.BecomeReseller.as_view(),name='become-reseller'),
  path('become-reseller-success/',views.BecomeResellerSuccess.as_view(),name='become-reseller-success'),
  
  # staff
  path('dashboard/orders/',views.StaffOrders.as_view(),name='staff-orders'),
  path('dashboard/orders/<id>/',views.StaffOrder.as_view(),name='staff-order'),
  path('dashboard/orders/<id>/comfirm/',views.StaffComfirmOrder.as_view(),name='staff-comfirm-order'),
  path('dashboard/orders/<id>/decline/',views.StaffDeclineOrder.as_view(),name='staff-decline-order'),
  path('dashboard/orders/<id>/approve/',views.StaffApproveOrder.as_view(),name='staff-approve-order'),
  path('dashboard/orders/<id>/cancel/',views.StaffCancelOrder.as_view(),name='staff-cancel-order'),
  path('dashboard/orders/<id>/deliver/',views.StaffDeliverOrder.as_view(),name='staff-deliver-order'),
  path('dashboard/orders/<id>/delivery-failed/',views.StaffDeliveryFailed.as_view(),name='staff-delivery-failed'),
  
  path('dashboard/withdraws/',views.StaffWithdraws.as_view(),name='staff-withdraws'),
  path('dashboard/withdraws/<pk>/approve/',views.StaffApproveWithdraw.as_view(),name='staff-approve-withdraws'),
  
  path('dashboard/sellers/',views.StaffSellers.as_view(),name='staff-sellers'),
  path('dashboard/sellers/requests/<pk>/',views.StaffSellerRequest.as_view(),name='staff-seller-request'),
  path('dashboard/sellers/<pk>/approve/',views.StaffApproveSeller.as_view(),name='staff-approve-seller'),
  path('dashboard/sellers/<pk>/decline/',views.StaffDeclineSellerRequest.as_view(),name='staff-decline-seller'),
  
  path('dashboard/resellers/',views.StaffResellers.as_view(),name='staff-resellers'),
  path('dashboard/resellers/<pk>/approve/',views.StaffApproveReseller.as_view(),name='staff-approve-reseller'),
  path('dashboard/resellers/<pk>/decline/',views.StaffDeclineResellerRequest.as_view(),name='staff-decline-reseller'),
  
  path('dashboard/currencies/',views.Currencies.as_view(),name='currencies'),
  path('dashboard/currencies/new/',views.NewCurrency.as_view(),name='new-currency'),
  path('dashboard/currencies/<id>/edit/',views.EditCurrency.as_view(),name='edit-currency'),
  path('dashboard/currencies/<id>/delete/',views.DeleteCurrency.as_view(),name='delete-currency'),
  
  path('dashboard/users/',views.StaffUsers.as_view(),name='staff-users'),
  path('dashboard/users/id/<user_id>/',views.StaffGeneralProfile.as_view(),name='staff-user'),
  path('dashboard/users/id/<user_id>/block-unblock/',views.StaffBlocOrUnblockUser.as_view(),name='staff-block-unblock-user'),
  
  path('dashboard/receiving-accounts/',views.StaffRecevingAccounts.as_view(),name='staff-receiving-accounts'),
  
  # seller
  path('dashboard/inventory/',views.Inventory.as_view(),name='inventory'),
  path('dashboard/new-inventory/',views.NewInventory.as_view(),name='new-inventory'),
  path('dashboard/inventory/<id>/images/',views.InventoryImages.as_view(),name='inventory-images'),
  path('dashboard/inventory/<id>/edit/',views.EditInventory.as_view(),name='edit-inventory'),
  path('dashboard/inventory/<id>/delete/',views.DeleteInventory.as_view(),name='delete-inventory'),
  
  path('dashboard/categories/',views.Categories.as_view(),name='categories'),
  path('dashboard/categories/new/',views.NewCategory.as_view(),name='new-category'),
  path('dashboard/categories/<id>/edit/',views.EditCategory.as_view(),name='edit-category'),
  path('dashboard/categories/<id>/delete/',views.DeleteCategory.as_view(),name='delete-category'),
  
  path('dashboard/purchases/',views.Purchases.as_view(),name='purchases'),
  path('dashboard/purchases/new/',views.NewPurchase.as_view(),name='new-purchase'),
  path('dashboard/purchases/<id>/edit/',views.EditPurchase.as_view(),name='edit-purchase'),
  path('dashboard/purchases/<id>/delete/',views.DeletePurchase.as_view(),name='delete-purchase'),
  
  path('dashboard/sales/',views.Sales.as_view(),name='sales'),
  path('dashboard/sales/wallet/<currency_code>/',views.StoreWallet.as_view(),name='store-wallet'),
  path('dashboard/sales/new/',views.NewSale.as_view(),name='new-sale'),
  path('dashboard/sales/<id>/',views.SalesItem.as_view(),name='sales-item'),
  path('dashboard/sales/<id>/edit/',views.EditSale.as_view(),name='edit-sale'),
  path('dashboard/sales/<id>/delete/',views.DeleteSale.as_view(),name='delete-sale'),
  path('dashboard/sales/order/<id>/',views.SalesOrder.as_view(),name='sales-order'),
  path('dashboard/sales/withdraw/<currency_id>/',views.StoreWithdraw.as_view(),name='sales-withdraw-request'),
  path('dashboard/sales/withdraw/cancel/<id>/',views.CancelWithdraw.as_view(),name='sales-cancel-withdraw-request'),
  
  path('dashboard/store-accounts/',views.StoreAccounts.as_view(),name='store-accounts'),
  path('dashboard/store-accounts/create/',views.CreateStoreAccount.as_view(),name='create-store-account'),
  
  # reseller
  path('dashboard/resale/',views.Resales.as_view(),name='resales'),
  path('dashboard/resale/wallet/<currency_code>/',views.UserWallet.as_view(),name='user-wallet'),
  path('dashboard/resale/<id>/delete',views.DeleteResale.as_view(),name='delete-resale'),
  path('dahsboard/resale/purchases/',views.ResalePurchases.as_view(),name='resale-purchases'),
  path('dahsboard/resale/purchases/<id>/',views.ResalePurchase.as_view(),name='resale-purchase'),
  path('dahsboard/resale/purchases/<id>/resale/',views.NewResale.as_view(),name='new-resale'),
  
  path('dashboard/reseller/cart/',views.ResellerCart.as_view(),name='reseller-cart'),
  path('dashboard/reseller/cart/clear/',views.ClearResellerCart.as_view(),name='clear-reseller-cart'),
  path('dashboard/reseller/cart/cod-checkout/',views.ResellerCODCheckout.as_view(),name='reseller-cod-checkout'),
  
  path('dashboard/user-accounts/',views.UserAccounts.as_view(),name='user-accounts'),
  path('dashboard/user-accounts/create/',views.CreateUserAccount.as_view(),name='create-user-account'),
]

dashboard/models.py
from django.db import models

class Option(models.Model):
  name=models.CharField(max_length=200)
  value=models.TextField()

  def __str__(self):
      return self.name
  

dashboard/forms.py
from django import forms
from dashboard import models, function

class GeneralOptionsForm(forms.Form):
  name=forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}),help_text='Enter a unique name for your store or brand.')
  tag_line=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}),help_text='Enter a catchy tag-line thats briefly describes your moto')
  description=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}),help_text='Describe your store.')
  site_mail=forms.EmailField(max_length=200,widget=forms.EmailInput(attrs={'class':'form-control'}),help_text='Site mail to be contacted on.')
  site_phone=forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}),help_text='Enter store phone number to be contacted on. Usually the help line.')
  business_address=forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}),help_text='Enter business address.')

  def save(self):
    for x in ['name','tag_line','description','site_mail','site_phone','business_address']:
      function.saveOption(x,self.cleaned_data[x])

class MailingForm(forms.Form):
  mailing_status=forms.ChoiceField(choices=(('ACTIVATED','Activated'),('DEACTIVATED','Deactivated')), widget=forms.Select(attrs={'class':'form-control'}))
  
  def save(self):
    for x in ['mailing_status']:
      function.saveOption(x,self.cleaned_data[x])

farozamart/forms.py
from django import forms
from farozamart import models

class GeneralOptionsForm(forms.Form):
  name=forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}))
  tag_line=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
  description=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))

  def save(self):
    models.Option.objects.create(name='name',value=self.cleaned_data['name'])
    models.Option.objects.create(name='tag_line',value=self.cleaned_data['tag_line'])
    models.Option.objects.create(name='description',value=self.cleaned_data['description'])

dashboard/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from dashboard.forms import GeneralOptionsForm, MailingForm
from dashboard.function import getOptions
from django.contrib import messages
from store import models as store_models
from store import functions as store_functions
from django.contrib.auth.models import User

# Create your views here.
class Dashboard(LoginRequiredMixin,UserPassesTestMixin,View):
  template_name='dashboard/dashboard.html'
  
  def test_func(self):
    return self.request.user.profile.is_seller or self.request.user.is_staff or self.request.user.profile.is_reseller
  
  def get(self, request):
    context={
      'sidebar_menu_dashboard_class':'active'
    }
    if request.user.is_staff:
      context['new_orders']=store_models.Order.objects.filter(draft=False,transaction=None).count()
      context['products']=store_models.Inventory.objects.all().count()
      context['sellers']=User.objects.filter(profile__is_seller=True).count()
      context['resellers']=User.objects.filter(profile__is_reseller=True).count()
    if request.user.profile.is_seller:
      context['sales']=store_functions.getUserSales(request.user).count()
      context['inventory']=request.user.store.inventory.all().count()
      context['active_purchases']=store_functions.getUserActivePurchases(request.user).count()
    messages.info(request,'Welcome to the dashboard!')
    return render(request,self.template_name,context)

class GeneralSettings(LoginRequiredMixin,View):
  template_name='dashboard/general-settings.html'
  
  def get(self,request):
    context={
      'form':GeneralOptionsForm(data=getOptions())
    }
    return render(request,self.template_name,context)
  
  def post(self,request):
    form = GeneralOptionsForm(data=request.POST)
    if form.is_valid():
      form.save()
      messages.success(request,'General options updated!')
      return redirect(reverse('dashboard:general-settings'))
    
    context={'form':form}
    return render(request,self.template_name,context)

class Mailing(LoginRequiredMixin,View):
  template_name='dashboard/mailing-settings.html'
  
  def get(self,request):
    context={
      'form':MailingForm(data=getOptions())
    }
    return render(request,self.template_name,context)
  
  def post(self,request):
    form = MailingForm(data=request.POST)
    if form.is_valid():
      form.save()
      messages.success(request,'Mailing options updated!')
      return redirect(reverse('dashboard:mailing-settings'))
    
    context={'form':form}
    return render(request,self.template_name,context)

farozamart/templates/dashboard/includes/messages.html
{% if messages %}
<div style="position: relative;">
  <!-- Position it -->
  <div style="">
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}{{ message.tags }}{% endif %}">
      {{message}}
      <a href="#" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

farozamart/templates/dashboard/includes/sidebar-menu.html
<ul class="sidebar-menu">
  <li class="header">MAIN NAVIGATION</li>
  <li class="{{sidebar_menu_dashboard_class}}">
    <a href="{% url "dashboard:dashboard" %}">
      <i class="fa fa-dashboard"></i> <span>Dashboard</span>
    </a>
  </li>
  <li>
    <a href="/">
      <i class="glyphicon glyphicon-home"></i> <span>Back To Site</span>
    </a>
  </li>

  {% if user.profile.is_seller %}
  <li class="header">SELLER</li>
  <li class="{{sidebar_menu_inventory_class}}">
    <a href="{% url "store:inventory" %}">
      <i class="glyphicon glyphicon-briefcase"></i> <span>Inventory</span>
    </a>
  </li>
  <li class="{{sidebar_menu_categories_class}}">
    <a href="{% url "store:categories" %}">
      <i class="glyphicon glyphicon-th"></i> <span>Categories</span>
    </a>
  </li>
  <li class="{{sidebar_menu_purchases_class}}">
    <a href="{% url "store:purchases" %}">
      <i class="glyphicon glyphicon-tags"></i> <span>Purchases</span>
    </a>
  </li>
  <li class="{{sidebar_menu_sales_class}}">
    <a href="{% url "store:sales" %}">
      <i class="glyphicon glyphicon-credit-card"></i> <span>Sales</span>
    </a>
  </li>
  <li class="{{sidebar_store_accounts_class}}">
    <a href="{% url "store:store-accounts" %}">
      <i class="glyphicon glyphicon-credit-card"></i> <span>Store Accounts</span>
    </a>
  </li>
  <!--<li class="{{sidebar_menu_steadfast_class}}">
    <a href="{% url "dropshipping:steadfast-delivery" %}">
      <i class="fa fa-shopping-cart"></i> <span>Steadfast Delivery</span>
    </a>
  </li>-->
  {% endif %}

  {% if user.profile.is_reseller %}
  <li class="header">RESELLER</li>
  <li class="{{sidebar_menu_resales_class}}">
    <a href="{% url "store:resales" %}">
      <i class="fa fa-suitcase"></i> <span>Resales</span>
    </a>
  </li>
  <li class="{{sidebar_menu_resale_purchases_class}}">
    <a href="{% url "store:resale-purchases" %}">
      <i class="glyphicon glyphicon-tags"></i> <span>Resale Purchases</span>
    </a>
  </li>
  <li class="{{sidebar_user_accounts_class}}">
    <a href="{% url "store:user-accounts" %}">
      <i class="glyphicon glyphicon-credit-card"></i> <span>User Accounts</span>
    </a>
  </li>
  <!--<li class="{{sidebar_menu_steadfast_class}}">
    <a href="{% url "dropshipping:steadfast-delivery" %}">
      <i class="fa fa-shopping-cart"></i> <span>Steadfast Delivery</span>
    </a>
  </li>-->
  {% endif %}

  {% if user.is_staff %}
  <li class="header">STAFF</li>
  <li class="{{sidebar_menu_staff_orders_class}}">
    <a href="{% url "store:staff-orders" %}">
      <i class="fa fa-shopping-cart"></i> <span>Orders</span>
    </a>
  </li>
  <li class="{{sidebar_menu_staff_withdraws_class}}">
    <a href="{% url "store:staff-withdraws" %}">
      <i class="fa fa-shopping-cart"></i> <span>Withdraws</span>
    </a>
  </li>
  <li class="{{sidebar_menu_staff_receiving_accounts_class}}">
    <a href="{% url "store:staff-receiving-accounts" %}">
      <i class="fa fa-shopping-cart"></i> <span>Receiving Accounts</span>
    </a>
  </li>
  <li class="{{sidebar_menu_staff_sellers_class}}">
    <a href="{% url "store:staff-sellers" %}">
      <i class="glyphicon glyphicon-gift"></i> <span>Sellers</span>
    </a>
  </li>
  <li class="{{sidebar_menu_staff_resellers_class}}">
    <a href="{% url "store:staff-resellers" %}">
      <i class="glyphicon glyphicon-gift"></i> <span>Resellers</span>
    </a>
  </li>
  <li class="{{sidebar_menu_users_class}}">
    <a href="{% url "store:staff-users" %}">
      <i class="glyphicon glyphicon-gift"></i> <span>Users</span>
    </a>
  </li>
  <li class="treeview">
    <a href="#">
      <i class="fa fa-gear"></i>
      <span>Settings</span>
      <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
      <li><a href="{% url "dashboard:general-settings" %}"><i class="fa fa-circle-o"></i> General</a></li>
      <li><a href="{% url "dashboard:mailing-settings" %}"><i class="fa fa-circle-o"></i> Mailing Settings</a></li>
      <li><a href="{% url "store:currencies" %}"><i class="fa fa-circle-o"></i> Currencies</a></li>
      <li><a href="{% url "dropshipping:steadfast-configuration" %}"><i class="fa fa-circle-o"></i> Steadfast Configuration</a></li>
      <li><a href="{% url "paymentgateway:cod-payment" %}"><i class="fa fa-circle-o"></i> COD Payment</a></li>
    </ul>
  </li>
  {% endif %}

  <li class="header">PROFILE</li>
  <li>
    <a href="{% url "accounts:profile" %}">
      <i class="fa fa-user"></i> <span>User Profile</span>
    </a>
  </li>
</ul>

farozamart/templates/dashboard/includes/top-menu.html
{% load static %}
<div class="navbar-custom-menu">
  <ul class="nav navbar-nav">
    {% if user.profile.is_reseller %}
    <li>
      <a href="{% url "store:reseller-cart" %}">
        <i class="fa fa-shopping-cart"></i>
        <span class="label label-success">{{cart_items_count}}</span>
      </a>
    </li>
    {% endif %}
    <!-- User Account: style can be found in dropdown.less -->
    <li class="dropdown user user-menu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="{{user.profile.picture.url}}" class="user-image" alt="User Image"/>
        <span class="hidden-xs">{{user.username}}</span>
      </a>
      <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
          <img src="{{user.profile.picture.url}}" class="img-circle" alt="User Image" />
          <p>
            {{user.username}}
            <small>{{user.profile.full_name}}</small>
          </p>
        </li>
        <!-- Menu Footer-->
        <li class="user-footer">
          <div class="pull-left">
            <a href="{% url "accounts:profile" %}" class="btn btn-default btn-flat">Profile</a>
          </div>
          <div class="pull-right">
            <a href="{% url "accounts:logout" %}" class="btn btn-default btn-flat">Sign out</a>
          </div>
        </li>
      </ul>
    </li>
  </ul>
</div>