dashboard/urls.py
from django.urls import path, include
from dashboard import views

app_name="dashboard"
urlpatterns = [
  path('',views.Dashboard.as_view(),name="dashboard"),
  path('settings/',views.GeneralSettings.as_view(),name='general-settings'),
  path('mailing-settings/',views.Mailing.as_view(),name='mailing-settings'),
]

farozamart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views
from store.api.routes import router as storeRouter
from accounts.api.routes import router as accountsRouter

router = DefaultRouter()
router.registry.extend(storeRouter.registry)
router.registry.extend(accountsRouter.registry)

urlpatterns = [
    path('favicon.ico',RedirectView.as_view(url=staticfiles_storage.url('favicon.png'))),
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('store/', include('store.urls')),
    path('dropshipping/',include('dropshipping.urls')),
    path('paymentgateway/',include('paymentgateway.urls')),
    path('api/v1/',include(router.urls)),
    path('api/auth/login/',views.obtain_auth_token)
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views as homeViews

app_name="home"
urlpatterns = [
    path('', homeViews.Home.as_view(), name='home'),
]

store/urls.py
from django.urls import path
from store import views

app_name='store'
urlpatterns = [
  # customer
  path('shop/',views.Shop.as_view(),name='shop'),
  path('shop/listing/<id>/',views.Listing.as_view(),name='listing'),
  path('shop/cart/',views.Cart.as_view(),name='cart'),
  path('shop/checkout/payment/',views.CheckoutPayment.as_view(),name='checkout-payment'),
  path('shop/cart/<id>/edit/',views.EditCartItem.as_view(),name='edit-cart-item'),
  path('shop/cart/<id>/delete/',views.DeleteCartItem.as_view(),name='delete-cart-item'),
  path('shop/cart/checkout/<order>/',views.Checkout.as_view(),name='checkout'),
  path('shop/cart/checkout-cod/<order>/',views.CheckoutCOD.as_view(),name='checkout-cod'),
  
  path('profile/orders/',views.CustomerOrders.as_view(),name='customer-orders'),
  path('profile/orders/<id>/',views.SingleCustomerOrder.as_view(),name='customer-order'),

  path('become-seller/',views.BecomeSeller.as_view(),name='become-seller'),
  path('become-reseller/',views.BecomeReseller.as_view(),name='become-reseller'),
  path('become-reseller-success/',views.BecomeResellerSuccess.as_view(),name='become-reseller-success'),
  
  # staff
  path('dashboard/orders/',views.StaffOrders.as_view(),name='staff-orders'),
  path('dashboard/orders/<id>/',views.StaffOrder.as_view(),name='staff-order'),
  path('dashboard/orders/<id>/comfirm/',views.StaffComfirmOrder.as_view(),name='staff-comfirm-order'),
  path('dashboard/orders/<id>/decline/',views.StaffDeclineOrder.as_view(),name='staff-decline-order'),
  path('dashboard/orders/<id>/approve/',views.StaffApproveOrder.as_view(),name='staff-approve-order'),
  path('dashboard/orders/<id>/cancel/',views.StaffCancelOrder.as_view(),name='staff-cancel-order'),
  path('dashboard/orders/<id>/deliver/',views.StaffDeliverOrder.as_view(),name='staff-deliver-order'),
  path('dashboard/orders/<id>/delivery-failed/',views.StaffDeliveryFailed.as_view(),name='staff-delivery-failed'),
  
  path('dashboard/withdraws/',views.StaffWithdraws.as_view(),name='staff-withdraws'),
  path('dashboard/withdraws/<pk>/approve/',views.StaffApproveWithdraw.as_view(),name='staff-approve-withdraws'),
  
  path('dashboard/sellers/',views.StaffSellers.as_view(),name='staff-sellers'),
  path('dashboard/sellers/requests/<pk>/',views.StaffSellerRequest.as_view(),name='staff-seller-request'),
  path('dashboard/sellers/<pk>/approve/',views.StaffApproveSeller.as_view(),name='staff-approve-seller'),
  path('dashboard/sellers/<pk>/decline/',views.StaffDeclineSellerRequest.as_view(),name='staff-decline-seller'),
  
  path('dashboard/resellers/',views.StaffResellers.as_view(),name='staff-resellers'),
  path('dashboard/resellers/<pk>/approve/',views.StaffApproveReseller.as_view(),name='staff-approve-reseller'),
  path('dashboard/resellers/<pk>/decline/',views.StaffDeclineResellerRequest.as_view(),name='staff-decline-reseller'),
  
  path('dashboard/currencies/',views.Currencies.as_view(),name='currencies'),
  path('dashboard/currencies/new/',views.NewCurrency.as_view(),name='new-currency'),
  path('dashboard/currencies/<id>/edit/',views.EditCurrency.as_view(),name='edit-currency'),
  path('dashboard/currencies/<id>/delete/',views.DeleteCurrency.as_view(),name='delete-currency'),
  
  path('dashboard/users/',views.StaffUsers.as_view(),name='staff-users'),
  path('dashboard/users/id/<user_id>/',views.StaffGeneralProfile.as_view(),name='staff-user'),
  path('dashboard/users/id/<user_id>/block-unblock/',views.StaffBlocOrUnblockUser.as_view(),name='staff-block-unblock-user'),
  
  path('dashboard/receiving-accounts/',views.StaffRecevingAccounts.as_view(),name='staff-receiving-accounts'),
  
  # seller
  path('dashboard/inventory/',views.Inventory.as_view(),name='inventory'),
  path('dashboard/new-inventory/',views.NewInventory.as_view(),name='new-inventory'),
  path('dashboard/inventory/<id>/images/',views.InventoryImages.as_view(),name='inventory-images'),
  path('dashboard/inventory/<id>/edit/',views.EditInventory.as_view(),name='edit-inventory'),
  path('dashboard/inventory/<id>/delete/',views.DeleteInventory.as_view(),name='delete-inventory'),
  
  path('dashboard/categories/',views.Categories.as_view(),name='categories'),
  path('dashboard/categories/new/',views.NewCategory.as_view(),name='new-category'),
  path('dashboard/categories/<id>/edit/',views.EditCategory.as_view(),name='edit-category'),
  path('dashboard/categories/<id>/delete/',views.DeleteCategory.as_view(),name='delete-category'),
  
  path('dashboard/purchases/',views.Purchases.as_view(),name='purchases'),
  path('dashboard/purchases/new/',views.NewPurchase.as_view(),name='new-purchase'),
  path('dashboard/purchases/<id>/edit/',views.EditPurchase.as_view(),name='edit-purchase'),
  path('dashboard/purchases/<id>/delete/',views.DeletePurchase.as_view(),name='delete-purchase'),
  
  path('dashboard/sales/',views.Sales.as_view(),name='sales'),
  path('dashboard/sales/wallet/<currency_code>/',views.StoreWallet.as_view(),name='store-wallet'),
  path('dashboard/sales/new/',views.NewSale.as_view(),name='new-sale'),
  path('dashboard/sales/<id>/',views.SalesItem.as_view(),name='sales-item'),
  path('dashboard/sales/<id>/edit/',views.EditSale.as_view(),name='edit-sale'),
  path('dashboard/sales/<id>/delete/',views.DeleteSale.as_view(),name='delete-sale'),
  path('dashboard/sales/order/<id>/',views.SalesOrder.as_view(),name='sales-order'),
  path('dashboard/sales/withdraw/<currency_id>/',views.StoreWithdraw.as_view(),name='sales-withdraw-request'),
  path('dashboard/sales/withdraw/cancel/<id>/',views.CancelWithdraw.as_view(),name='sales-cancel-withdraw-request'),
  
  path('dashboard/store-accounts/',views.StoreAccounts.as_view(),name='store-accounts'),
  path('dashboard/store-accounts/create/',views.CreateStoreAccount.as_view(),name='create-store-account'),
  
  # reseller
  path('dashboard/resale/',views.Resales.as_view(),name='resales'),
  path('dashboard/resale/wallet/<currency_code>/',views.UserWallet.as_view(),name='user-wallet'),
  path('dashboard/resale/<id>/delete',views.DeleteResale.as_view(),name='delete-resale'),
  path('dahsboard/resale/purchases/',views.ResalePurchases.as_view(),name='resale-purchases'),
  path('dahsboard/resale/purchases/<id>/',views.ResalePurchase.as_view(),name='resale-purchase'),
  path('dahsboard/resale/purchases/<id>/resale/',views.NewResale.as_view(),name='new-resale'),
  
  path('dashboard/reseller/cart/',views.ResellerCart.as_view(),name='reseller-cart'),
  path('dashboard/reseller/cart/clear/',views.ClearResellerCart.as_view(),name='clear-reseller-cart'),
  path('dashboard/reseller/cart/cod-checkout/',views.ResellerCODCheckout.as_view(),name='reseller-cod-checkout'),
  
  path('dashboard/user-accounts/',views.UserAccounts.as_view(),name='user-accounts'),
  path('dashboard/user-accounts/create/',views.CreateUserAccount.as_view(),name='create-user-account'),
]

store/api/routes.py
from rest_framework.routers import DefaultRouter
from store.api import views as apiviews

router = DefaultRouter()
router.register(r'store/listing',apiviews.ListingViewSet,basename='store')
router.register(r'store/cart',viewset=apiviews.CartViewSet,basename='cart')

store/api/views.py
from rest_framework.viewsets import ViewSet
from rest_framework.response import Response
from rest_framework.decorators import action
from store import models, functions
from store.api import serializers
from django.shortcuts import get_object_or_404

class ListingViewSet(ViewSet):
  def list(self,request,*args,**kwargs):
    listing = models.Purchase.objects.all()
    listingSerializer = serializers.PurchaseSerializer(listing, many=True)
    return Response(listingSerializer.data)
  
  def retrieve(self,request,pk,*args,**kwargs):
    listing = models.Purchase.objects.get(pk=pk)
    listingSerializer = serializers.PurchaseSerializer(listing)
    return Response(listingSerializer.data)
  
  @action(detail=True,methods=['post'])
  def add_to_cart(self,request,pk):
    listing = models.Purchase.objects.get(pk=pk)
    serializer = serializers.AddToCartSerializer(user=request.user,listing=listing,data=request.POST)
    if serializer.is_valid():
      serializer.save()
      sales = models.Sale.objects.filter(user=request.user,cart=True,approved=False)
      saleSerializer = serializers.SalesSerializer(sales,many=True)
      return Response(saleSerializer.data)
    return Response(serializer.error_messages,status=500)

class CartViewSet(ViewSet):
  @action(detail=False,methods=['get'])
  def get_cart(self,request,*args,**kwargs):
    order = request.user.orders.get(draft=True)
    orderSerializer = serializers.OrderSerializer(order)
    return Response(orderSerializer.data)
  
  @action(detail=True,methods=['get'])
  def cod_checkout(self,request,pk,*args,**kwargs):
    order = functions.CODPayment(pk=pk)
    orderSerializer = serializers.OrderSerializer(order)
    return Response(orderSerializer.data)
    

store/templates/store/staff/approve-order.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Order {{order.id}}{% endblock title %}

{% block contentHeader %}
<h1>
  Approve order {{order.id}}
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li><a href="{% url "store:staff-orders" %}"><i class="fa fa-dashboard"></i> Orders</a></li>
  <li class="active">{{order.id}}</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "includes/form.html" with method="POST" action="" submitText="Save" %}
{% endblock content %}

store/templates/store/staff/general-profile.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Profile {{obj.id}}{% endblock title %}

{% block contentHeader %}
<h1>
  Profile {{obj.id}}
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li class="active">Profile {{obj.id}}</li>
</ol>
{% endblock contentHeader %}

{% block content %}
<div class="box">
  <div class="box-header">
    <h3 class="box-title">{{obj}}</h3>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <td colspan=2><h3>User</h3></td>
      </tr>
      <tr>
        <th>ID</th>
        <td>{{obj.id}}</td>
      </tr>
      <tr>
        <th>Username</th>
        <td>{{obj.username}}</td>
      </tr>
      <tr>
        <th>E-mail</th>
        <td>{{obj.email}}</td>
      </tr>
      <tr>
        <td colspan=2><h3>Profile</h3></td>
      </tr>
      <tr>
        <th>Name</th>
        <td>{{obj.profile.full_name}}</td>
      </tr>
      <tr>
        <th>Gender</th>
        <td>{{obj.profile.gender}}</td>
      </tr>
      <tr>
        <th>Address</th>
        <td>{{obj.profile.address}}</td>
      </tr>
      <tr>
        <th>E-mail</th>
        <td>{{obj.profile.email}}</td>
      </tr>
      <tr>
        <th>Phone</th>
        <td>{{obj.profile.phone}}</td>
      </tr>
      <tr>
        <th>Whatsapp</th>
        <td>{{obj.profile.whatsapp}}</td>
      </tr>
      <tr>
        <th>Facebook</th>
        <td>{{obj.profile.facebook}}</td>
      </tr>
      <tr>
        <th>Reseller</th>
        <td>{{obj.profile.is_reseller}}</td>
      </tr>
      {% if obj.store %}
      <tr>
        <td colspan=2><h3>Store</h3></td>
      </tr>
      <tr>
        <th>Store Name</th>
        <td>{{obj.store.name}}</td>
      </tr>
      <tr>
        <th>Store Description</th>
        <td>{{obj.store.description}}</td>
      </tr>
      <tr>
        <th>Store Address</th>
        <td>{{obj.store.address}}</td>
      </tr>
      <tr>
        <th>Store Trade licence</th>
        <td>{{obj.store.trade_licence}}</td>
      </tr>
      {% endif %}
    </table>
    {% if obj.profile.is_seller %}
    <h3>Store Accounts</h3>
    {% include "store/tables/accounts.html" with accounts=obj.store.store_accounts.all %}
    {% endif %}
    {% if obj.profile.is_reseller %}
    <h3>User Accounts</h3>
    {% include "store/tables/accounts.html" with accounts=obj.user_accounts.all %}
    {% endif %}
  </div><!-- /.box-body -->
</div><!-- /.box -->
{% if user.is_staff %}
{% if obj.becomeseller %}
<a class="btn btn-success" href="{% url "store:staff-approve-seller" pk=obj.becomeseller.id %}">Approve Seller</a>
{% endif %}
{% if obj.becomereseller %}
<a class="btn btn-success" href="{% url "store:staff-approve-reseller" pk=obj.becomereseller.id %}">Approve Reseller</a>
{% endif %}
{% endif %}

{{ obj.becomereseller.get }}

{% endblock content %}

store/templates/store/staff/orders.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Orders{% endblock title %}

{% block contentHeader %}
<h1>
  Orders
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>-->
  <li class="active">Orders</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "store/tables/orders.html" %}
{% endblock content %}

store/templates/store/staff/receiving-accounts.html
{% extends "dashboard/base.html" %}

{% block title %}{{ block.super }} | Receiving Accounts{% endblock title %}

{% block contentHeader %}
<h1>
  Receiving Accounts
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li class="active">Receiving Accounts</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "store/tables/accounts.html" %}
{% endblock content %}

store/templates/store/staff/resellers.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Resellers{% endblock title %}

{% block contentHeader %}
<h1>
  Resellers
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li class="active">Resellers</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "store/tables/staff/reseller-requests.html" %}
{% include "store/tables/staff/resellers.html" %}
{% endblock content %}

store/templates/store/staff/seller-request.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Seller request {{seller.id}}{% endblock title %}

{% block contentHeader %}
<h1>
  Seller request {{seller.id}}
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li><a href="{% url "store:staff-sellers" %}"><i class="fa fa-dashboard"></i> Sellers</a></li>
  <li class="active">Seller request {{seller.id}}</li>
</ol>
{% endblock contentHeader %}

{% block content %}
<div class="box">
  <div class="box-header">
    <h3 class="box-title">{{seller}}</h3>
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <td>{{seller.id}}</td>
      </tr>
      <tr>
        <th>Name</th>
        <td>{{seller.profile.full_name}}</td>
      </tr>
    </table>
  </div><!-- /.box-body -->
</div><!-- /.box -->
{{seller}}
<a class="btn btn-success" href="{% url "store:staff-approve-seller" pk=seller.id %}">Approve</a>
{% endblock content %}

store/templates/store/staff/sellers.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Sellers{% endblock title %}

{% block contentHeader %}
<h1>
  Sellers
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li class="active">Sellers</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "store/tables/staff/seller-requests.html" %}
{% include "store/tables/staff/sellers.html" %}
{% endblock content %}

store/templates/store/staff/staff-order.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Order {{order.id}}{% endblock title %}

{% block contentHeader %}
<h1>
  Order {{order.id}}
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li><a href="{% url "store:staff-orders" %}"><i class="fa fa-dashboard"></i> Orders</a></li>
  <li class="active">Order {{order.id}}</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "store/tables/general-order.html" %}
{% endblock content %}

store/templates/store/staff/users.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Users{% endblock title %}

{% block contentHeader %}
<h1>
  Users
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li class="active">Users</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "store/tables/staff/users.html" %}
{% endblock content %}

store/templates/store/staff/withdraws.html
{% extends "dashboard/base.html" %}

{% block title %}{{block.super}} | Dashboard - Withdraws{% endblock title %}

{% block contentHeader %}
<h1>
  Withdraws
</h1>
<ol class="breadcrumb">
  <li><a href="{% url "dashboard:dashboard" %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li class="active">Withdraws</li>
</ol>
{% endblock contentHeader %}

{% block content %}
{% include "store/tables/staff/withdraws.html" %}
{% endblock content %}